---
apiVersion: v1
kind: Service
metadata:
  name: kakeibo-exporter-api
spec:
  selector:
    app: kakeibo-exporter-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kakeibo-exporter-api
  name: kakeibo-exporter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakeibo-exporter-api
  template:
    metadata:
      labels:
        app: kakeibo-exporter-api
    spec:
      containers:
        - name: kakeibo-exporter
          image: faruryo/kakeibo-exporter
          imagePullPolicy: Never
          command: ["python", "-m", "kakeibo_exporter", "run-api"]
          envFrom:
            - configMapRef:
                name: mysql-env
          volumeMounts:
            - name: google-credential
              mountPath: "/app/credentials.json"
              subPath: credentials.json
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        - name: google-credential
          secret:
            secretName: google-credential
